site_name: "Infrastructure Automation: Syllabus"
site_url: https://hogenttin.github.io/infra-syllabus/
repo_url: https://github.com/HoGentTIN/infra-syllabus/
edit_uri: edit/main/docs/
nav:
  - Studiewijzer: index.md
  - Intro: intro.md
  - Containers: containers.md
  - CICD: ci-cd.md
  - Troubleshooting: troubleshooting.md
  - ConfigMgmt: cfgmgmt.md
  - Monitoring: monitoring.md
